In [4]:
import zipfile as zf
files = zf.ZipFile("/content/archive (1).zip", 'r')
files.extractall('my_data')
files.close()

In [5]:
import cv2
import os
import numpy as np

def load_your_image_data(image_dir):
    image_files = os.listdir(image_dir)
    image_data = []

    for file_name in image_files:
        image_path = os.path.join(image_dir, file_name)
        image = cv2.imread(image_path)  # Load image using OpenCV
        image_data.append(image)

    return np.array(image_data)

In [30]:
image_dir = '/content/my_data'
X_images = load_your_image_data(image_dir)

In [31]:
X_images

array([[[[163, 217, 250],
         [166, 220, 253],
         [166, 219, 252],
         ...,
         [101, 109, 126],
         [100, 108, 125],
         [ 98, 106, 123]],

        [[166, 220, 253],
         [158, 211, 244],
         [153, 206, 239],
         ...,
         [100, 108, 125],
         [ 97, 105, 122],
         [ 94, 102, 119]],

        [[155, 208, 241],
         [140, 191, 224],
         [140, 191, 224],
         ...,
         [100, 108, 125],
         [108, 116, 133],
         [102, 110, 127]],

        ...,

        [[163, 193, 220],
         [167, 197, 224],
         [173, 203, 230],
         ...,
         [ 26,  25,  29],
         [ 28,  27,  31],
         [ 36,  35,  39]],

        [[161, 190, 217],
         [159, 188, 215],
         [161, 190, 217],
         ...,
         [ 44,  39,  41],
         [ 41,  36,  38],
         [ 46,  41,  43]],

        [[161, 190, 217],
         [157, 186, 213],
         [155, 184, 211],
         ...,
         [ 44,  39,  41],
        

In [8]:
def load_your_crop_yield_data():
    # Replace with your code to load actual crop yield data
    # Make sure y_crop is an array of crop yield values
    y_crop = np.array([100, 200, 150])
    return y_crop

In [9]:
import numpy as np
import cv2
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [32]:
# Load your own image data (replace with your actual image loading code)
# Make sure X_images is an array of shape (num_samples, image_height, image_width, 3)
# X_images = load_your_image_data()

# Apply K-Means clustering for tree detection
num_clusters = 2
kmeans_images = KMeans(n_clusters=num_clusters, random_state=0)

# Flatten images and apply K-Means clustering
X_flattened = X_images.reshape(-1, 3)
tree_labels = kmeans_images.fit_predict(X_flattened)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [33]:
tree_labels

array([1, 1, 1, ..., 0, 0, 0], dtype=int32)

In [11]:
# Synthesize a super-feature vector
super_feature_vector = []

for i in range(3):
    features = []

    # Convert image to the appropriate data type
    scaled_image = (X_images[i] * 255).astype(np.uint8)

    # Convert scaled image to grayscale
    gray_image = cv2.cvtColor(scaled_image, cv2.COLOR_RGB2GRAY)

    # Apply threshold to create a binary image
    ret, binary_image = cv2.threshold(gray_image, 128, 255, cv2.THRESH_BINARY)

    # Extract geometric features (e.g., bounding box dimensions)
    contours, _ = cv2.findContours(binary_image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if contours:
        x, y, w, h = cv2.boundingRect(contours[0])
        features.extend([w, h])
    else:
        features.extend([0, 0])

    super_feature_vector.append(features)

super_feature_vector = np.array(super_feature_vector)

In [12]:
super_feature_vector

array([[3, 1],
       [2, 1],
       [3, 1]])

In [13]:
# Load your actual crop yield data (replace with your data loading code)
# Make sure y_crop is an array of crop yield values
y_crop = load_your_crop_yield_data()

In [14]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(super_feature_vector, y_crop, test_size=0.2, random_state=0)


In [15]:
# Train a linear regression model for crop estimation
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [16]:
# Predict crop yield on the testing set
y_pred = regressor.predict(X_test)

In [17]:
# Evaluate the regression model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")


Mean Squared Error: 2499.9999999999945


In [18]:
y_pred

array([100.])

In [19]:
y_test

array([150])

In [20]:
from matplotlib import pyplot as plt

In [21]:
img= '/content/my_data/DJI_0279.JPG'

In [22]:
import cv2

# Load an image
image_path = "/content/my_data/DJI_0280.JPG"
image = cv2.imread(image_path)

# Get the image dimensions (height and width)
image_height, image_width, _ = image.shape

In [23]:
import numpy as np
import cv2
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Generate synthetic image data (replace with your actual image data)
num_samples = 100
image_height = 256
image_width = 256
X_images = np.random.rand(num_samples, image_height, image_width, 3)

# Apply K-Means clustering for tree detection
num_clusters = 2
kmeans_images = KMeans(n_clusters=num_clusters, random_state=0)

# Flatten images and apply K-Means clustering
X_flattened = X_images.reshape(-1, 3)
tree_labels = kmeans_images.fit_predict(X_flattened)

# Synthesize a super-feature vector
super_feature_vector = []

# ...
for i in range(num_samples):
    features = []

    # Convert image to the appropriate data type
    scaled_image = (X_images[i] * 255).astype(np.uint8)

    # Convert scaled image to grayscale
    gray_image = cv2.cvtColor(scaled_image, cv2.COLOR_RGB2GRAY)

    # Apply threshold to create a binary image
    ret, binary_image = cv2.threshold(gray_image, 128, 255, cv2.THRESH_BINARY)

    # Extract geometric features (e.g., bounding box dimensions)
    contours, _ = cv2.findContours(binary_image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if contours:
        x, y, w, h = cv2.boundingRect(contours[0])
        features.extend([w, h])
    else:
        features.extend([0, 0])

    super_feature_vector.append(features)

super_feature_vector = np.array(super_feature_vector)
# ...


# Generate synthetic crop yield data (replace with your actual data)
y_crop = np.random.rand(num_samples) * 1000

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(super_feature_vector, y_crop, test_size=0.2, random_state=0)

# Train a linear regression model for crop estimation
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Predict crop yield on the testing set
y_pred = regressor.predict(X_test)

# Evaluate the regression model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Mean Squared Error: 64025.5432042881


In [24]:
image_dir = '/content/my_data'
X_images = load_your_image_data(image_dir)

In [25]:
y_foreground = [1, 0, 1]
y_regression = [20, 15, 30]

In [26]:
import os
import cv2
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense


# Step 1: Data loading and preprocessing

# Path to the folder containing the images
image_folder = '/content/my_data'

# Load and preprocess images
images = []
for filename in os.listdir(image_folder):
    if filename.endswith(".JPG") or filename.endswith(".png"):
        img = cv2.imread(os.path.join(image_folder, filename))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # Convert to RGB
        img = cv2.resize(img, (224, 224))  # Resize images to a consistent size
        images.append(img)

# Step 2: K-Means clustering for enhanced segmentation

def kmeans_segmentation(image, num_clusters=3):
    reshaped_img = image.reshape((-1, 3))
    kmeans = KMeans(n_clusters=num_clusters, random_state=0).fit(reshaped_img)
    segmented_img = kmeans.cluster_centers_[kmeans.labels_]
    segmented_img = segmented_img.reshape(image.shape)
    return segmented_img

segmented_images = [kmeans_segmentation(img) for img in images]

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [27]:
np.array(segmented_images)

array([[[[226.34289277, 197.81204883, 155.99054994],
         [226.34289277, 197.81204883, 155.99054994],
         [226.34289277, 197.81204883, 155.99054994],
         ...,
         [150.60053033, 127.02563268, 102.74278936],
         [150.60053033, 127.02563268, 102.74278936],
         [150.60053033, 127.02563268, 102.74278936]],

        [[150.60053033, 127.02563268, 102.74278936],
         [226.34289277, 197.81204883, 155.99054994],
         [226.34289277, 197.81204883, 155.99054994],
         ...,
         [150.60053033, 127.02563268, 102.74278936],
         [150.60053033, 127.02563268, 102.74278936],
         [150.60053033, 127.02563268, 102.74278936]],

        [[226.34289277, 197.81204883, 155.99054994],
         [226.34289277, 197.81204883, 155.99054994],
         [226.34289277, 197.81204883, 155.99054994],
         ...,
         [150.60053033, 127.02563268, 102.74278936],
         [ 61.77748847,  55.28641571,  49.77659574],
         [150.60053033, 127.02563268, 102.74278936]],