In [1]:
import zipfile as zf
files = zf.ZipFile("/content/archive (1).zip", 'r')
files.extractall('my_data')
files.close()

In [ ]:
import cv2
import os
import numpy as np

def load_your_image_data(image_dir):
    image_files = os.listdir(image_dir)
    image_data = []

    for file_name in image_files:
        image_path = os.path.join(image_dir, file_name)
        image = cv2.imread(image_path)  # Load image using OpenCV
        image_data.append(image)

    return np.array(image_data)

In [ ]:
image_dir = '/content/my_data'
X_images = load_your_image_data(image_dir)

In [ ]:
X_images

array([[[[151, 202, 235],
         [155, 206, 239],
         [152, 205, 238],
         ...,
         [ 67,  76,  86],
         [ 59,  68,  78],
         [ 57,  66,  76]],

        [[165, 218, 251],
         [172, 225, 255],
         [170, 223, 255],
         ...,
         [ 60,  68,  81],
         [ 54,  63,  73],
         [ 58,  67,  77]],

        [[152, 205, 238],
         [158, 211, 244],
         [155, 209, 242],
         ...,
         [ 66,  74,  87],
         [ 53,  61,  74],
         [ 48,  56,  69]],

        ...,

        [[161, 181, 206],
         [147, 167, 192],
         [145, 163, 186],
         ...,
         [ 75,  67,  68],
         [ 75,  67,  68],
         [ 83,  75,  76]],

        [[149, 169, 194],
         [158, 178, 203],
         [155, 175, 200],
         ...,
         [ 84,  76,  77],
         [ 78,  70,  71],
         [ 80,  72,  73]],

        [[140, 160, 185],
         [145, 165, 190],
         [146, 166, 191],
         ...,
         [ 90,  82,  83],
        

In [ ]:
def load_your_crop_yield_data():
    # Replace with your code to load actual crop yield data
    # Make sure y_crop is an array of crop yield values
    y_crop = np.array([100, 200, 150])
    return y_crop

In [ ]:
import numpy as np
import cv2
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [ ]:
# Load your own image data (replace with your actual image loading code)
# Make sure X_images is an array of shape (num_samples, image_height, image_width, 3)
# X_images = load_your_image_data()

# Apply K-Means clustering for tree detection
num_clusters = 2
kmeans_images = KMeans(n_clusters=num_clusters, random_state=0)

# Flatten images and apply K-Means clustering
X_flattened = X_images.reshape(-1, 3)
tree_labels = kmeans_images.fit_predict(X_flattened)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [ ]:
# Synthesize a super-feature vector
super_feature_vector = []

for i in range(3):
    features = []

    # Convert image to the appropriate data type
    scaled_image = (X_images[i] * 255).astype(np.uint8)

    # Convert scaled image to grayscale
    gray_image = cv2.cvtColor(scaled_image, cv2.COLOR_RGB2GRAY)

    # Apply threshold to create a binary image
    ret, binary_image = cv2.threshold(gray_image, 128, 255, cv2.THRESH_BINARY)

    # Extract geometric features (e.g., bounding box dimensions)
    contours, _ = cv2.findContours(binary_image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if contours:
        x, y, w, h = cv2.boundingRect(contours[0])
        features.extend([w, h])
    else:
        features.extend([0, 0])

    super_feature_vector.append(features)

super_feature_vector = np.array(super_feature_vector)

In [ ]:
super_feature_vector

array([[2, 1],
       [1, 1],
       [2, 1]])

In [ ]:
# Load your actual crop yield data (replace with your data loading code)
# Make sure y_crop is an array of crop yield values
y_crop = load_your_crop_yield_data()

In [ ]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(super_feature_vector, y_crop, test_size=0.2, random_state=0)


In [ ]:
# Train a linear regression model for crop estimation
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [ ]:
# Predict crop yield on the testing set
y_pred = regressor.predict(X_test)

In [ ]:
# Evaluate the regression model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")


Mean Squared Error: 2499.9999999999945


In [ ]:
y_pred

array([200.])

In [ ]:
y_test

array([150])

In [ ]:
from matplotlib import pyplot as plt

In [ ]:
img= '/content/my_data/DJI_0279.JPG'

In [ ]:
import cv2

# Load an image
image_path = "/content/my_data/DJI_0280.JPG"
image = cv2.imread(image_path)

# Get the image dimensions (height and width)
image_height, image_width, _ = image.shape

In [ ]:
import numpy as np
import cv2
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Generate synthetic image data (replace with your actual image data)
num_samples = 100
image_height = 256
image_width = 256
X_images = np.random.rand(num_samples, image_height, image_width, 3)

# Apply K-Means clustering for tree detection
num_clusters = 2
kmeans_images = KMeans(n_clusters=num_clusters, random_state=0)

# Flatten images and apply K-Means clustering
X_flattened = X_images.reshape(-1, 3)
tree_labels = kmeans_images.fit_predict(X_flattened)

# Synthesize a super-feature vector
super_feature_vector = []

# ...
for i in range(num_samples):
    features = []

    # Convert image to the appropriate data type
    scaled_image = (X_images[i] * 255).astype(np.uint8)

    # Convert scaled image to grayscale
    gray_image = cv2.cvtColor(scaled_image, cv2.COLOR_RGB2GRAY)

    # Apply threshold to create a binary image
    ret, binary_image = cv2.threshold(gray_image, 128, 255, cv2.THRESH_BINARY)

    # Extract geometric features (e.g., bounding box dimensions)
    contours, _ = cv2.findContours(binary_image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if contours:
        x, y, w, h = cv2.boundingRect(contours[0])
        features.extend([w, h])
    else:
        features.extend([0, 0])

    super_feature_vector.append(features)

super_feature_vector = np.array(super_feature_vector)
# ...


# Generate synthetic crop yield data (replace with your actual data)
y_crop = np.random.rand(num_samples) * 1000

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(super_feature_vector, y_crop, test_size=0.2, random_state=0)

# Train a linear regression model for crop estimation
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Predict crop yield on the testing set
y_pred = regressor.predict(X_test)

# Evaluate the regression model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Mean Squared Error: 84820.2299941559


In [ ]:
image_dir = '/content/my_data'
X_images = load_your_image_data(image_dir)

In [ ]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Flatten, Dense

# Generate synthetic image data (replace with your actual image data loading code)
num_samples = 100
image_height = 256
image_width = 256
X_images = np.random.rand(num_samples, image_height, image_width, 3)

# Generate synthetic crop yield data (replace with your actual crop yield data loading code)
y_crop = np.random.rand(num_samples) * 1000

# Apply K-Means clustering for tree detection
num_clusters = 2
kmeans_images = KMeans(n_clusters=num_clusters, random_state=0)

# Flatten images and apply K-Means clustering
X_flattened = X_images.reshape(-1, 3)
tree_labels = kmeans_images.fit_predict(X_flattened)

# Convert tree labels to one-hot encoding
tree_labels_onehot = np.eye(num_clusters)[tree_labels]

# Split data into training and testing sets
X_train_cls, X_test_cls, y_train_cls, y_test_cls = train_test_split(X_images, tree_labels_onehot, test_size=0.2, random_state=0)

# Train the classification model
model = Sequential([
    Flatten(input_shape=(image_height, image_width, 3)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(num_clusters, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train_cls, y_train_cls, epochs=10, batch_size=32, validation_data=(X_test_cls, y_test_cls))


In [2]:
y_foreground = [1, 0, 1]
y_regression = [20, 15, 30]

In [10]:
import os
import cv2
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense


# Step 1: Data loading and preprocessing

# Path to the folder containing the images
image_folder = '/content/my_data'

# Load and preprocess images
images = []
for filename in os.listdir(image_folder):
    if filename.endswith(".JPG") or filename.endswith(".png"):
        img = cv2.imread(os.path.join(image_folder, filename))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # Convert to RGB
        img = cv2.resize(img, (224, 224))  # Resize images to a consistent size
        images.append(img)

# Step 2: K-Means clustering for enhanced segmentation

def kmeans_segmentation(image, num_clusters=3):
    reshaped_img = image.reshape((-1, 3))
    kmeans = KMeans(n_clusters=num_clusters, random_state=0).fit(reshaped_img)
    segmented_img = kmeans.cluster_centers_[kmeans.labels_]
    segmented_img = segmented_img.reshape(image.shape)
    return segmented_img

segmented_images = [kmeans_segmentation(img) for img in images]

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [11]:
np.array(segmented_images)

array([[[[225.78031496, 197.77349081, 157.55728346],
         [225.78031496, 197.77349081, 157.55728346],
         [151.23649682, 127.86735593, 104.11924521],
         ...,
         [151.23649682, 127.86735593, 104.11924521],
         [151.23649682, 127.86735593, 104.11924521],
         [151.23649682, 127.86735593, 104.11924521]],

        [[225.78031496, 197.77349081, 157.55728346],
         [225.78031496, 197.77349081, 157.55728346],
         [151.23649682, 127.86735593, 104.11924521],
         ...,
         [ 59.37487843,  53.54559737,  48.68781327],
         [ 59.37487843,  53.54559737,  48.68781327],
         [151.23649682, 127.86735593, 104.11924521]],

        [[225.78031496, 197.77349081, 157.55728346],
         [225.78031496, 197.77349081, 157.55728346],
         [151.23649682, 127.86735593, 104.11924521],
         ...,
         [151.23649682, 127.86735593, 104.11924521],
         [ 59.37487843,  53.54559737,  48.68781327],
         [ 59.37487843,  53.54559737,  48.68781327]],

In [16]:
images = []
for filename in os.listdir(image_folder):
    if filename.endswith(".JPG") or filename.endswith(".png"):
        img = cv2.imread(os.path.join(image_folder, filename))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # Convert to RGB
        img = cv2.resize(img, (224, 224))  # Resize images to a consistent size
        images.append(img)

# Step 2: K-Means clustering for enhanced segmentation

def kmeans_segmentation(image, num_clusters=3):
    reshaped_img = image.reshape((-1, 3))
    kmeans = KMeans(n_clusters=num_clusters, random_state=0).fit(reshaped_img)
    segmented_img = kmeans.cluster_centers_[kmeans.labels_]
    segmented_img = segmented_img.reshape(image.shape)
    return segmented_img

segmented_images = [kmeans_segmentation(img) for img in images]

# Step 3: Extract features and create super-feature vector

def extract_features(image):
    # Extract statistical features (mean, standard deviation)
    mean_rgb = np.mean(image, axis=(0, 1))
    std_rgb = np.std(image, axis=(0, 1))

    # Extract geometric features (aspect ratio, area, etc.)
    height, width, _ = image.shape
    aspect_ratio = width / height
    area = height * width

    return np.concatenate((mean_rgb, std_rgb, [aspect_ratio, area]))

feature_vectors = [extract_features(img) for img in segmented_images]

# Step 4: Deep learning-based classification model for foreground tree detection

# Assuming you have 3 images and their corresponding foreground labels (0 or 1)
# Example: 1 for foreground tree detected, 0 for no foreground tree detected
y_foreground = [1, 0, 1]  # One foreground tree detected, no foreground tree, one foreground tree

# Split the data into training and testing sets
X_train_foreground, X_test_foreground, y_train_foreground, y_test_foreground = train_test_split(np.array(segmented_images), y_foreground, test_size=0.2, random_state=0)

# Build a CNN model for foreground tree classification
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train_foreground, y_train_foreground, epochs=10, batch_size=32, validation_data=(X_test_foreground, np.array(y_test_foreground)))


# # Step 3: Extract features and create super-feature vector

# def extract_features(image):
#     # Extract statistical features (mean, standard deviation)
#     mean_rgb = np.mean(image, axis=(0, 1))
#     std_rgb = np.std(image, axis=(0, 1))

#     # Extract geometric features (aspect ratio, area, etc.)
#     height, width, _ = image.shape
#     aspect_ratio = width / height
#     area = height * width

#     return np.concatenate((mean_rgb, std_rgb, [aspect_ratio, area]))

# feature_vectors = [extract_features(img) for img in segmented_images]

# # Step 4: Deep learning-based classification model for foreground tree detection

# # Assuming you have a labeled dataset for foreground tree detection (X_foreground, y_foreground)
# # Here, X_foreground represents the images and y_foreground represents the binary labels (0 or 1)

# y_foreground = [ 1,0,1]  # One foreground tree detected, no foreground tree, one foreground tree

# # Split the data into training and testing sets
# X_train_foreground, X_test_foreground, y_train_foreground, y_test_foreground = train_test_split(np.array(segmented_images), y_foreground, test_size=0.2, random_state=0)

# # Build a CNN model for foreground tree classification
# model = Sequential()
# model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)))
# model.add(MaxPooling2D((2, 2)))
# model.add(Conv2D(64, (3, 3), activation='relu'))
# model.add(MaxPooling2D((2, 2)))
# model.add(Conv2D(128, (3, 3), activation='relu'))
# model.add(Flatten())
# model.add(Dense(64, activation='relu'))
# model.add(Dense(1, activation='sigmoid'))

# model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# # Train the model
# model.fit(X_train_foreground, y_train_foreground, epochs=10, batch_size=32, validation_data=(X_test_foreground, y_test_foreground))

# Step 5: Regression-based crop estimation using extracted features

# Assuming you have a dataset for crop yield estimation (X_regression, y_regression)
# Here, X_regression represents the extracted feature vectors and y_regression represents the crop yield values

# Split the data into training and testing sets
X_train_regression, X_test_regression, y_train_regression, y_test_regression = train_test_split(np.array(feature_vectors), y_regression, test_size=0.2, random_state=0)

# Train a RandomForestRegressor for crop yield estimation
regressor = RandomForestRegressor(random_state=0)
regressor.fit(X_train_regression, y_train_regression)

# Evaluate the regression model
y_pred_regression = regressor.predict(X_test_regression)
mse_regression = mean_squared_error(y_test_regression, y_pred_regression)

print(f"Mean Squared Error for Crop Yield Estimation: {mse_regression}")

# Step 6: Crop yield estimation for new images

new_image = cv2.imread('path_to_new_image.jpg')
new_image = cv2.cvtColor(new_image, cv2.COLOR_BGR2RGB)
segmented_new_image = kmeans_segmentation(new_image)
new_features = extract_features(segmented_new_image)

# Use the trained regression model to estimate crop yield
estimated_yield = regressor.predict([new_features])

print(f"Estimated Crop Yield: {estimated_yield[0]}")


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


ValueError: ignored